name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install native dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y libpango1.0-dev libaosd-dev python-cairo-dev

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython

    - name: Build
      run: |
        python setup.py build_ext
